# Generated by Django 6.0.2 on 2026-03-01 20:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_membership',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
